name: LMLT_Large_DF2K_X3
model_type: SRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /data/SR/df2k/datasets/DF2K/DF2K_train_HR_sub
    dataroot_lq: /data/SR/df2k/datasets/DF2K/DF2K_train_LR_bicubic/X3_sub
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  # we use multiple validation datasets. The SR benchmark datasets can be download from: https://cv.snu.ac.kr/research/EDSR/benchmark.tar
  val:
    name: DIV2K_val100
    type: PairedImageDataset
    dataroot_gt: /data/ECCV/SR/dataset_img/testsets/urban100/HR
    dataroot_lq: /data/ECCV/SR/dataset_img/testsets/urban100/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

# network structures
network_g:
  type: LMLT
  dim: 84
  n_blocks: 8
  ffn_scale: 2.0
  upscaling_factor: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: False
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 3
      test_y_channel: False
      better: higher  # the higher, the better. Default: higher
    # ssim:
    #   type: calculate_ssim
    #   crop_border: 3
    #   test_y_channel: False
    #   better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
